
TARGET_DIR="$SNANA_LSST_ROOT/lcmerge"

cp OUT3_FLUXERRMODEL/FLUXERRMODEL_FAKE.DAT \
   $TARGET_DIR/FLUXERRMODEL_DC2_FAKE.DAT

cp OUT3_FLUXERRMODEL/FLUXERRMODEL_SIM.DAT \
   $TARGET_DIR/FLUXERRMODEL_DC2_SIM.DAT

ls -l $TARGET_DIR/FLUXERRMODEL*

